#!/bin/bash

set -e

export ROOT_DIR=$(readlink -e $(dirname $0) | sed 's|/scripts||')

source ${ROOT_DIR}/scripts/common_pkg_build.sh

# debuild default options
DEB_OPTS="-us -uc"

# Also allow the user to create just the source package (skip build process)
if [ "$1" == source ]; then
	prepare_tarball archive
	DEB_OPTS="-S $DEB_OPTS"
else
	prepare_tarball
fi


pushd ${ROOT_DIR}/${package}-${version}
cp -r ${ROOT_DIR}/pkg/debian .

current=$(echo ${version} | awk -F . '{printf("%d\n", (($1 * 100) + $2))}')
rename 's,([^-\.]*)(.*),${1}'"${current}"'${2},' debian/*ofp*

sed -i "s:\(.*ofp\)\([^\.]\|$\):\1${current}\2:g" debian/control
sed -i "s:\(.*ofp\)\(.*\):\1${current}\2:g" debian/rules

if [ $(egrep "\.([a-z0-9]{8}\>|dirty)" .scmversion |wc -l) -gt 0 ]; then
	export DEBFULLNAME="Donald Duck"
	export DEBEMAIL="donald.duck@linaro.org"
	dch --newversion ${version}-1 --urgency low "not a official release!"
fi

debuild ${DEB_OPTS}
popd
popd
